// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/

//@version=5

// 定義脚本在圖表中顯示的名稱
indicator("MACD #1")
fast = 12  // 定義快綫
slow = 26  // 定義慢綫
fastMA = ta.ema(close, fast) // 定義快綫 ema （收盤價，fast）
slowMA = ta.ema(close, slow) // 定義慢綫 ems （收盤價，slow）
macd = fastMA - slowMA       // 快綫 - 慢綫 為macd
signal = ta.ema(macd, 9)     //
plot(macd, color = color.blue)  // 畫圖 macd 這個價格 顔色為 blue
plot(signal, color = color.orange)  // 畫圖 signal 這個價格 顔色為 blue


// pro 版本
// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
//@version=5
// 定義脚本在圖表中顯示的名稱
indicator("MACD #2")
fastInput = input(12, "Fast length")  // 輸入一個快綫
slowInput = input(26, "Slow length")  // 輸入一個慢綫
[macdLine, signalLine, histLine] = ta.macd(close, fastInput, slowInput, 9) // 通過close 計算
plot(macdLine, color = color.blue)
plot(signalLine, color = color.orange)