

// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © worldlinkopen

//@version=5
strategy("MACD #2", overlay = true, initial_capital=1000)
import TradingView/Strategy/3
fast = 12  // 定義快綫
slow = 26  // 定義慢綫
fastMA = ta.ema(close, fast) // 定義快綫 ema （收盤價，fast）
slowMA = ta.ema(close, slow) // 定義慢綫 ems （收盤價，slow）
p1  = plot(fastMA, color = color.blue)  // 畫圖 macd 這個價格 顔色為 blue
p2 = plot(slowMA, color = color.orange)  // 畫圖 signal 這個價格 顔色為 blue

up = ta.crossover(fastMA, slowMA) // 記錄buy點
down = ta.crossover(slowMA,fastMA) // 記錄sell 點

jk = ta.atr(14) >  ta.atr(14)[2]  // 這跟k 》 前2跟k

if up and jk
    strategy.entry("order key", strategy.long,  1)

if down
    strategy.close("order key", "close")