[ServiceConfiguration]
Port="8182"
Debug=true

[PostgresConfiguration]
Host="192.168.40.198"
Port=5532
User="root"
Password="L8onP2L3"
DBName="trade"

[RedisConfiguration]
Addr="192.168.40.198:6379"
Db=1

[LoggerConfiguration]
Filename="logs/real.log"
Level="debug"

[OpenTelemetryConfiguration]
[OpenTelemetryConfiguration.Traces]
HTTPEndpoint = "192.168.40.198:5081"
Path="/api/default/traces"
Authorization = "Basic Z29vZ2xlQGdvb2dsZS5jb206UHZmS0hvQ05vMXc0bHk5SQ=="

[OpenTelemetryConfiguration.Logs]
HTTPEndpoint = "http://192.168.40.198:5081/api/default/real/_json"
User="google@google.com"
Password="PvfKHoCNo1w4ly9I"
File="logs/real.log"